version: "3.8"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    volumes:
      - ./.env:/app/.env
    command: ["./my_payments"]
    depends_on:
      - db
  db:
    image: postgres:latest
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: mysecretpassword
      POSTGRES_DB: payments
    ports:
      - "5432:5432"
    volumes:
      - payments_data:/var/lib/postgresql/data

volumes:
  payments_data:
